// <auto-generated />
using System;
using BlazorAppExam.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppExam.Migrations
{
    [DbContext(typeof(StudentsDb))]
    partial class StudentsDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppExam.Models.Students", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Class = 6,
                            Name = "Bikes"
                        },
                        new
                        {
                            StudentId = 2,
                            Class = 6,
                            Name = "Abdullah"
                        },
                        new
                        {
                            StudentId = 3,
                            Class = 7,
                            Name = "Jannat"
                        },
                        new
                        {
                            StudentId = 4,
                            Class = 7,
                            Name = "Bikes"
                        },
                        new
                        {
                            StudentId = 5,
                            Class = 7,
                            Name = "Farzana"
                        },
                        new
                        {
                            StudentId = 6,
                            Class = 7,
                            Name = "Hasib"
                        });
                });

            modelBuilder.Entity("BlazorAppExam.Models.StudentsMarks", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObtainedNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsStudentId")
                        .HasColumnType("int");

                    b.Property<int>("TotalNumber")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("StudentsMarks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ExamName = "Final",
                            ObtainedNumber = 600,
                            StudentId = 1,
                            TotalNumber = 800
                        },
                        new
                        {
                            ID = 2,
                            ExamName = "External",
                            ObtainedNumber = 600,
                            StudentId = 2,
                            TotalNumber = 800
                        },
                        new
                        {
                            ID = 3,
                            ExamName = "Evidence",
                            ObtainedNumber = 600,
                            StudentId = 3,
                            TotalNumber = 800
                        });
                });

            modelBuilder.Entity("BlazorAppExam.Models.StudentsMarks", b =>
                {
                    b.HasOne("BlazorAppExam.Models.Students", "Students")
                        .WithMany("studentsMarks")
                        .HasForeignKey("StudentsStudentId");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("BlazorAppExam.Models.Students", b =>
                {
                    b.Navigation("studentsMarks");
                });
#pragma warning restore 612, 618
        }
    }
}
